require File.join(File.dirname(__FILE__), "test_generator_helper.rb")

class TestSinatraAppGenerator < Test::Unit::TestCase
  include RubiGen::GeneratorTestHelper

  def setup
    bare_setup
  end

  def teardown
    bare_teardown
  end

  # Some generator-related assertions:
  #   assert_generated_file(name, &block) # block passed the file contents
  #   assert_directory_exists(name)
  #   assert_generated_class(name, &block)
  #   assert_generated_module(name, &block)
  #   assert_generated_test_for(name, &block)
  # The assert_generated_(class|module|test_for) &block is passed the body of the class/module within the file
  #   assert_has_method(body, *methods) # check that the body has a list of methods (methods with parentheses not supported yet)
  #
  # Other helper methods are:
  #   app_root_files - put this in teardown to show files generated by the test method (e.g. p app_root_files)
  #   bare_setup - place this in setup method to create the APP_ROOT folder for each test
  #   bare_teardown - place this in teardown method to destroy the TMP_ROOT or APP_ROOT folder after each test

  def test_generate_app_without_options
    run_generator('sinatra_app', [APP_ROOT], sources)
    assert_basic_paths_and_files
    assert_generated_file 'views/layout.erb'
    assert_generated_file 'views/index.erb'
    assert_generated_file "test/test_#{app_name}.rb" do |test_contents|
      assert_match(/def test/, test_contents)
    end    
  end

  def test_generate_app_with_vendor_option
    run_generator('sinatra_app', [APP_ROOT, '--vendor'], sources)
    assert_basic_paths_and_files
    assert_directory_exists 'vendor/sinatra/lib'
  end
  
  def test_generate_app_with_tiny_option
    run_generator('sinatra_app', [APP_ROOT, '--tiny'], sources)
    assert_generated_file   'config.ru'
    assert_generated_file   'app.rb'
    assert_generated_file   'Rakefile'
  end
  
  def test_generate_app_with_init_option
    run_generator('sinatra_app', [APP_ROOT, '-i'], sources)
    assert_basic_paths_and_files
    assert_directory_exists '.git'
  end
  
  def test_generate_app_with_rspect_test_option
    run_generator('sinatra_app', [APP_ROOT, '--test=rspec'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'test/test_helper.rb' do |helper_contents|
      assert_match(/sinatra\/test\/rspec/, helper_contents)
    end
    assert_generated_file "test/test_#{app_name}.rb" do |test_contents|
      assert_match(/describe/, test_contents)
    end
  end
  
  def test_generate_app_with_spec_test_option
    run_generator('sinatra_app', [APP_ROOT, '--test=spec'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'test/test_helper.rb' do |helper_contents|
      assert_match(/sinatra\/test\/spec/, helper_contents)
    end
    assert_generated_file "test/test_#{app_name}.rb" do |test_contents|
      assert_match(/describe/, test_contents)
    end
  end
  
  def test_generate_app_with_shoulda_test_option
    run_generator('sinatra_app', [APP_ROOT, '--test=shoulda'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'test/test_helper.rb' do |helper_contents|
      assert_match(/sinatra\/test\/unit/, helper_contents)
      assert_match(/shoulda/, helper_contents)
    end
    assert_generated_file "test/test_#{app_name}.rb" do |test_contents|
      assert_match(/context/, test_contents)
    end
  end
  
  def test_generate_app_with_test_unit_option
    run_generator('sinatra_app', [APP_ROOT, '--test=unit'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'test/test_helper.rb' do |helper_contents|
      assert_match(/sinatra\/test\/unit/, helper_contents)
    end
    assert_generated_file "test/test_#{app_name}.rb" do |test_contents|
      assert_match(/def test/, test_contents)
    end
  end

  def test_generate_app_with_views_haml_option
    run_generator('sinatra_app', [APP_ROOT, '--views=erb'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'app.rb' do |app_contents|
      assert_match(/erb \:index/, app_contents)
    end
    assert_generated_file 'views/layout.erb'
    assert_generated_file 'views/index.erb'
  end
  
  def test_generate_app_with_views_haml_option
    run_generator('sinatra_app', [APP_ROOT, '--views=haml'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'app.rb' do |app_contents|
      assert_match(/haml \:index/, app_contents)
    end
    assert_generated_file 'views/layout.haml'
    assert_generated_file 'views/index.haml'
  end

  def test_generate_app_with_views_builder_option
    run_generator('sinatra_app', [APP_ROOT, '--views=builder'], sources)
    assert_basic_paths_and_files
    assert_generated_file 'app.rb' do |app_contents|
      assert_match(/builder \:index/, app_contents)
    end
    assert_generated_file 'views/index.builder'
  end
  
  def test_generate_app_with_scripts_option
    run_generator('sinatra_app', [APP_ROOT, '--scripts'], sources)
    assert_basic_paths_and_files
    assert_directory_exists 'script'
    assert_generated_file 'script/destroy'
    assert_generated_file 'script/generate'
  end
  
  private
  def assert_basic_paths_and_files
    assert_directory_exists 'lib'
    assert_directory_exists 'test'
    assert_directory_exists 'public'
    assert_directory_exists 'views'
    assert_generated_file   'config.ru'
    assert_generated_file   'app.rb'
    assert_generated_file   'Rakefile'
    assert_generated_module  "lib/#{app_name}"
  end
    
  
  def sources
    [RubiGen::PathSource.new(:test, File.join(File.dirname(__FILE__),"..", generator_path))]
  end

  def app_name
    File.basename(APP_ROOT)
  end

  def generator_path
    "app_generators"
  end
end
